name: Test Scheduled Workflow

on:
  push:
    branches:
      - main
  schedule:
    # For testing, you might want to use a more frequent schedule
    # For example, every 10 minutes: */10 * * * *
    - cron: '*/10 * * * *'  # Or use your actual desired schedule

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print time
        run: |
          echo "Workflow triggered at: $(date)"
          echo "Trigger type: ${{ github.event_name }}"